const ROOT_URL =
  process.env.NEXT_PUBLIC_APP_URL ||
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "") ||
  "https://base-mini-app-flame.vercel.app"

export const minikitConfig = {
  accountAssociation: {
    header: "eyJmaWQiOjQ0MTUxMiwidHlwZSI6ImF1dGgiLCJrZXkiOiIweDY5RDUxQjE4QzFFZkU4OEE5MzAyYTAzQTYwMTI3ZDk4ZUQzRDMwN0QifQ",
    payload: "eyJkb21haW4iOiJiYXNlLW1pbmktYXBwLWZsYW1lLnZlcmNlbC5hcHAifQ",
    signature: "MHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjYwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDFkZmVlOTAyZWU4YWVlNjMzODRjN2UzMjg5NGFlMTcwMTIyNGI1NWEwZTA2ZGEyZjc0N2I2MDRjNGM0M2ZkZjExMDVkMDk1NGYxMWFlYzA4N2YxMjRmMmQ2YzI2NWRiOGNkMzkzMzg0NmUwN2VlZGQ3MTE4MWJhNGI4ZGNjOWM1ZjAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjVmMTk4MDg2YjJkYjE3MjU2NzMxYmM0NTY2NzNiOTZiY2VmMjNmNTFkMWZiYWNkZDdjNDM3OWVmNjU0NjU1NzJmMWQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjc3YjIyNzQ3OTcwNjUyMjNhMjI3NzY1NjI2MTc1NzQ2ODZlMmU2NzY1NzQyMjJjMjI2MzY4NjE2YzZjNjU2ZTY3NjUyMjNhMjIzNDMzNmY0YjUwNTU0MjUyNTc3NzRmNmE2ZTU0NTUzODc0NzY1MjU1NmU0NjcyNmU0MjZhNjY0ODZlNTQ2MjJkNGY1NTRhNzEzODM0N2E1YTU4NzU2NzIyMmMyMjZmNzI2OTY3Njk2ZTIyM2EyMjY4NzQ3NDcwNzMzYTJmMmY2YjY1Nzk3MzJlNjM2ZjY5NmU2MjYxNzM2NTJlNjM2ZjZkMjIyYzIyNjM3MjZmNzM3MzRmNzI2OTY3Njk2ZTIyM2E2NjYxNmM3MzY1MmMyMjZmNzQ2ODY1NzI1ZjZiNjU3OTczNWY2MzYxNmU1ZjYyNjU1ZjYxNjQ2NDY1NjQ1ZjY4NjU3MjY1MjIzYTIyNjQ2ZjIwNmU2Zjc0MjA2MzZmNmQ3MDYxNzI2NTIwNjM2YzY5NjU2ZTc0NDQ2MTc0NjE0YTUzNGY0ZTIwNjE2NzYxNjk2ZTczNzQyMDYxMjA3NDY1NmQ3MDZjNjE3NDY1MmUyMDUzNjU2NTIwNjg3NDc0NzA3MzNhMmYyZjY3NmY2ZjJlNjc2YzJmNzk2MTYyNTA2NTc4MjI3ZDAwMDAwMDAwMDAwMDAwMDAwMA"
  },
  baseBuilder: {
    allowedAddresses: ["0x69D51B18C1EfE88A9302a03A60127d98eD3D307D"]
  },
  miniapp: {
    version: "1",
    name: "OSINT Mini",
    subtitle: "Professional OSINT Platform",
    description: "Advanced OSINT tools and analytics on Base blockchain for professional intelligence gathering",
    tagline: "Intelligence Made Simple",
    homeUrl: ROOT_URL,
    iconUrl: `${ROOT_URL}/favicon.ico`,
    splashImageUrl: `${ROOT_URL}/images/osint-identity-card.png`,
    splashBackgroundColor: "#0052FF",
    webhookUrl: `${ROOT_URL}/api/webhook`,
    heroImageUrl: `${ROOT_URL}/images/osint-identity-card.png`,
    ogTitle: "OSINT Mini - Base App",
    ogDescription: "Professional OSINT intelligence platform built on Base blockchain",
    ogImageUrl: `${ROOT_URL}/images/osint-identity-card.png`,
    primaryCategory: "utility",
    tags: ["osint", "intelligence", "analytics", "blockchain", "tools"]
  }
} as const
