const ROOT_URL =
  process.env.NEXT_PUBLIC_APP_URL ||
  (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "") ||
  "https://base-mini-app-flame.vercel.app"

export const minikitConfig = {
  accountAssociation: {
    header: "eyJmaWQiOjQ0MTUxMiwidHlwZSI6ImF1dGgiLCJrZXkiOiIweDY5RDUxQjE4QzFFZkU4OEE5MzAyYTAzQTYwMTI3ZDk4ZUQzRDMwN0QifQ",
    payload: "eyJkb21haW4iOiJ4NDAybmV3LnZlcmNlbC5hcHAifQ",
    signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAC6XtDGqoxJA4-Bnlh-JjPEqfQooAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAy7dTu9nQhmkC5rNpg8oRa7fbP-jMiSAdEUnoBgsELh9btJJ512P_yyw14Tc11fdYmt4MhIgjnYA-ftAtKc-uXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAvi1eKIJu0ASD2ocrV3yJBFE7wKnhWwqMROytRWUz0BEOrSzgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABZd5fV1TQ8_YPJSYGPNgvdCrZchMMxqcfMCrYRKy-c2obqLqVRKLkhFGFWogqhF0JneFzrVwyzghJcvILu6ScWwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAl8ZgIay2xclZzG8RWZzuWvO8j9R0fus3XxDee9lRlVy8dAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKeyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiWmlHeHpvRDM2cGt2TW1pbWRhNF9ZNVZFYjJMTkVQRjFuSFBCMngtanBKbyIsIm9yaWdpbiI6Imh0dHBzOi8va2V5cy5jb2luYmFzZS5jb20iLCJjcm9zc09yaWdpbiI6ZmFsc2V9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSS"
  },
  baseBuilder: {
    allowedAddresses: ["0x69D51B18C1EfE88A9302a03A60127d98eD3D307D"]
  },
  miniapp: {
    version: "1",
    name: "OSINT Mini",
    subtitle: "Professional OSINT Platform",
    description: "Advanced OSINT tools and analytics on Base blockchain for professional intelligence gathering",
    tagline: "Intelligence Made Simple",
    homeUrl: ROOT_URL,
    iconUrl: `${ROOT_URL}/favicon.ico`,
    splashImageUrl: `${ROOT_URL}/images/osint-identity-card.png`,
    splashBackgroundColor: "#0052FF",
    webhookUrl: `${ROOT_URL}/api/webhook`,
    heroImageUrl: `${ROOT_URL}/images/osint-identity-card.png`,
    ogTitle: "OSINT Mini - Base App",
    ogDescription: "Professional OSINT intelligence platform built on Base blockchain",
    ogImageUrl: `${ROOT_URL}/images/osint-identity-card.png`,
    primaryCategory: "utility",
    tags: ["osint", "intelligence", "analytics", "blockchain", "tools"]
  }
} as const
